import * as THREE from "three";
import { LevelDefinition, LevelId } from "./types";

const v3 = (x: number, y: number, z: number) => new THREE.Vector3(x, y, z);

export const LEVEL_ORDER: LevelId[] = [
  "relay-loop",
  "uplink-split",
  "blackout-run",
];

export const LEVEL_DEFINITIONS: Record<LevelId, LevelDefinition> = {
  "relay-loop": {
    id: "relay-loop",
    name: "Relay Loop",
    subtitle: "Chain the terminals. Learn the fast lines.",
    objectiveKind: "terminal-sequence",
    floorSize: new THREE.Vector2(38, 38),
    floorColor: 0x2a2c36,
    backgroundColor: 0x10182d,
    fogFar: 54,
    spawnPoints: [
      { position: v3(-12.5, 0.1, 12.5), rotation: 0 },
      { position: v3(12.5, 0.1, -12.5), rotation: Math.PI },
    ],
    structures: [
      { id: "relay-center", size: v3(7, 3.2, 7), position: v3(0, 0, 0), color: 0x5e2a11, role: "cover" },
      { id: "relay-east", size: v3(3, 2.2, 8), position: v3(11, 0, 2), color: 0x69421a, role: "cover" },
      { id: "relay-west", size: v3(3, 2.2, 8), position: v3(-11, 0, -2), color: 0x69421a, role: "cover" },
      { id: "relay-north", size: v3(10, 1.6, 2), position: v3(4, 0, -11), color: 0x4c5f74, role: "cover" },
      { id: "relay-south", size: v3(9, 1.5, 2), position: v3(-4, 0, 11), color: 0x4c5f74, role: "cover" },
      { id: "slide-gate-top", size: v3(5, 0.85, 1.8), position: v3(-2, 1.1, -8), color: 0x6c7689, role: "overhead" },
      { id: "slide-gate-left", size: v3(1, 2.2, 2), position: v3(-4.4, 0, -8), color: 0x454f66, role: "wall" },
      { id: "slide-gate-right", size: v3(1, 2.2, 2), position: v3(0.4, 0, -8), color: 0x454f66, role: "wall" },
      { id: "relay-inner-cover", size: v3(2.5, 1.6, 2.5), position: v3(9, 0, -9), color: 0x6c4d2f, role: "cover" },
      { id: "relay-inner-cover-2", size: v3(2.5, 1.6, 2.5), position: v3(-10, 0, 9), color: 0x6c4d2f, role: "cover" },
    ],
    navWaypoints: [
      v3(-13, 0.1, -13),
      v3(0, 0.1, -14),
      v3(13, 0.1, -10),
      v3(13, 0.1, 10),
      v3(0, 0.1, 14),
      v3(-13, 0.1, 10),
      v3(-7, 0.1, -7),
      v3(8, 0.1, 8),
    ],
    botSpawns: [
      {
        id: "relay-bot-1",
        spawn: { position: v3(12, 0.1, 12), rotation: -Math.PI * 0.65 },
        archetype: "anchor",
        patrolRoute: [v3(12, 0.1, 12), v3(8, 0.1, -10), v3(2, 0.1, -14), v3(-8, 0.1, -10)],
      },
      {
        id: "relay-bot-2",
        spawn: { position: v3(-12, 0.1, -12), rotation: Math.PI * 0.24 },
        archetype: "rusher",
        patrolRoute: [v3(-12, 0.1, -12), v3(-14, 0.1, 6), v3(-5, 0.1, 13), v3(6, 0.1, 13)],
      },
    ],
    reinforcementSpawns: [
      {
        id: "relay-bot-3",
        spawn: { position: v3(13, 0.1, 2), rotation: -Math.PI / 2 },
        archetype: "disruptor",
        elite: true,
        patrolRoute: [v3(13, 0.1, 2), v3(10, 0.1, -12), v3(2, 0.1, -6), v3(8, 0.1, 10)],
      },
    ],
    interactables: [
      {
        id: "relay-terminal-a",
        label: "Terminal A",
        hint: "Boot the west relay and expose the next lane.",
        type: "terminal",
        position: v3(-12, 0.1, -11),
        holdDuration: 0.8,
        rotation: Math.PI / 3,
      },
      {
        id: "relay-terminal-b",
        label: "Terminal B",
        hint: "Bridge the east choke and draw security off center.",
        type: "terminal",
        position: v3(13, 0.1, -10),
        holdDuration: 0.8,
        rotation: -Math.PI * 0.72,
      },
      {
        id: "relay-terminal-c",
        label: "Terminal C",
        hint: "Prime the final node to arm the extraction beacon.",
        type: "terminal",
        position: v3(10, 0.1, 11),
        holdDuration: 0.8,
        rotation: Math.PI * 0.84,
      },
    ],
    holdZones: [],
    jumpPads: [
      {
        id: "relay-pad-1",
        label: "Lift Pad",
        position: v3(-13, 0.1, 9),
        radius: 1.45,
        impulse: v3(11.5, 7.2, -6.5),
      },
    ],
    weaponPickups: [
      {
        id: "relay-arc-smg",
        weaponId: "arc-smg",
        label: "Arc SMG",
        detail: "Fast flank weapon near the jump-pad route.",
        position: v3(-13, 0.1, 9),
      },
      {
        id: "relay-scattershot",
        weaponId: "scattershot",
        label: "Scattershot",
        detail: "Close-range spread gun tucked into the slide gate.",
        position: v3(-2, 0.1, -8),
      },
      {
        id: "relay-carbine-refill",
        weaponId: "vanguard-carbine",
        label: "Carbine Refill",
        detail: "Duplicate pickup converts into a full rifle magazine.",
        position: v3(12, 0.1, -2),
      },
    ],
    extractionZone: {
      label: "Extract",
      hint: "Hold inside the beacon to upload the relay chain and leave.",
      position: v3(-14.5, 0.1, 15),
      radius: 1.75,
      holdDuration: 1.2,
    },
    objectiveDefensePoints: [v3(-10, 0.1, -7), v3(11, 0.1, -8), v3(8, 0.1, 8)],
    optionalObjectives: [
      {
        id: "relay-elite-wave",
        kind: "elite-wave",
        label: "Elite Trace",
        hint: "Sync Terminal B to bait the elite hunter into the east lane.",
        position: v3(13, 0.1, -10),
        radius: 2.3,
        scoreValue: 350,
        linkedSpawnIds: ["relay-bot-3"],
        onlyAfterInteractableId: "relay-terminal-b",
      },
      {
        id: "relay-jump-cache",
        kind: "bonus-cache",
        label: "Flux Cache",
        hint: "Ride the lift-pad flank for a timed score cache before extraction.",
        position: v3(-13, 0.1, 9),
        radius: 1.8,
        scoreValue: 225,
        unlockObjectiveIndex: 0,
        timeLimit: 12,
      },
      {
        id: "relay-fast-extract",
        kind: "timed-extract",
        label: "Speed Upload",
        hint: "Finish the relay loop under the target split for a final payout.",
        position: v3(-14.5, 0.1, 15),
        radius: 2.1,
        scoreValue: 275,
        onlyAfterExtractionUnlocked: true,
        timeLimit: 54,
      },
    ],
    medalThresholds: {
      bronze: 1750,
      silver: 2100,
      gold: 2550,
      s: 3000,
      targetTime: 56,
    },
    checkpoints: [
      {
        id: "relay-start",
        label: "Insertion",
        objectiveIndex: 0,
        spawn: { position: v3(-12.5, 0.1, 12.5), rotation: 0 },
      },
      {
        id: "relay-breach",
        label: "East Breach",
        objectiveIndex: 2,
        spawn: { position: v3(10, 0.1, -6), rotation: Math.PI * 0.9 },
      },
    ],
    bossEncounter: {
      bossId: "relay-warden",
      displayName: "Relay Warden",
      weaponType: "conductor-beam",
      spawn: { position: v3(0, 0.1, 0), rotation: Math.PI },
      checkpoint: { position: v3(6, 0.1, 8), rotation: -2.2 },
      lockdownSegments: [
        { id: "relay-lock-north", position: v3(0, 1.2, -14.4), size: v3(9, 2.4, 0.6), color: 0x67cfff },
        { id: "relay-lock-south", position: v3(0, 1.2, 14.4), size: v3(9, 2.4, 0.6), color: 0x67cfff },
        { id: "relay-lock-east", position: v3(14.4, 1.2, 0), size: v3(0.6, 2.4, 9), color: 0x67cfff },
        { id: "relay-lock-west", position: v3(-14.4, 1.2, 0), size: v3(0.6, 2.4, 9), color: 0x67cfff },
      ],
      health: 560,
      scoreValue: 900,
      xpValue: 120,
      introText: "Relay Warden online. Beam grid armed.",
    },
  },
  "uplink-split": {
    id: "uplink-split",
    name: "Uplink Split",
    subtitle: "Chain the uplink terminals. Reclaim the lanes.",
    objectiveKind: "terminal-sequence",
    floorSize: new THREE.Vector2(42, 34),
    floorColor: 0x262a32,
    backgroundColor: 0x111b30,
    fogFar: 56,
    spawnPoints: [
      { position: v3(0, 0.1, 14), rotation: 0 },
      { position: v3(0, 0.1, -14), rotation: Math.PI },
    ],
    structures: [
      { id: "uplink-catwalk", size: v3(18, 0.8, 4), position: v3(0, 2.1, 0), color: 0x55647d, role: "platform" },
      { id: "uplink-left-cover", size: v3(3, 2, 7), position: v3(-12, 0, -1), color: 0x744019, role: "cover" },
      { id: "uplink-right-cover", size: v3(3, 2, 7), position: v3(12, 0, 1), color: 0x744019, role: "cover" },
      { id: "uplink-mid-left", size: v3(4, 1.2, 2), position: v3(-5, 0, 0), color: 0x4f5a6c, role: "cover" },
      { id: "uplink-mid-right", size: v3(4, 1.2, 2), position: v3(5, 0, 0), color: 0x4f5a6c, role: "cover" },
      { id: "uplink-back-left", size: v3(5, 1.6, 2), position: v3(-15, 0, 10), color: 0x644728, role: "cover" },
      { id: "uplink-back-right", size: v3(5, 1.6, 2), position: v3(15, 0, -10), color: 0x644728, role: "cover" },
      { id: "uplink-dash-lane", size: v3(2, 1.4, 10), position: v3(0, 0, -9), color: 0x3e4658, role: "cover" },
    ],
    navWaypoints: [
      v3(-16, 0.1, 10),
      v3(-12, 0.1, -10),
      v3(0, 0.1, -12),
      v3(12, 0.1, -10),
      v3(16, 0.1, 10),
      v3(0, 2.9, 0),
      v3(-7, 0.1, 8),
      v3(7, 0.1, -8),
    ],
    botSpawns: [
      {
        id: "uplink-bot-1",
        spawn: { position: v3(-15, 0.1, -10), rotation: Math.PI / 4 },
        archetype: "anchor",
        patrolRoute: [v3(-15, 0.1, -10), v3(-12, 0.1, 6), v3(-6, 0.1, 10), v3(0, 2.9, 0)],
      },
      {
        id: "uplink-bot-2",
        spawn: { position: v3(15, 0.1, 10), rotation: -Math.PI * 0.75 },
        archetype: "disruptor",
        patrolRoute: [v3(15, 0.1, 10), v3(9, 0.1, -4), v3(3, 0.1, -10), v3(0, 2.9, 0)],
      },
      {
        id: "uplink-bot-3",
        spawn: { position: v3(0, 2.9, 0), rotation: Math.PI },
        archetype: "anchor",
        patrolRoute: [v3(0, 2.9, 0), v3(-8, 0.1, 9), v3(8, 0.1, -9), v3(0, 0.1, 12)],
      },
    ],
    reinforcementSpawns: [
      {
        id: "uplink-hunter-left",
        spawn: { position: v3(-4, 0.1, 14), rotation: Math.PI },
        archetype: "rusher",
        patrolRoute: [v3(-4, 0.1, 14), v3(0, 0.1, 4), v3(8, 0.1, -6), v3(0, 2.9, 0)],
      },
      {
        id: "uplink-hunter-right",
        spawn: { position: v3(4, 0.1, -14), rotation: 0 },
        archetype: "rusher",
        patrolRoute: [v3(4, 0.1, -14), v3(0, 0.1, -4), v3(-8, 0.1, 6), v3(0, 2.9, 0)],
      },
    ],
    interactables: [
      {
        id: "uplink-terminal-a",
        label: "Terminal A",
        hint: "Stabilize the west uplink terminal to reopen the center lane.",
        type: "terminal",
        position: v3(-14, 0.1, 11),
        holdDuration: 0.8,
        rotation: Math.PI * 0.18,
      },
      {
        id: "uplink-terminal-b",
        label: "Terminal B",
        hint: "Sync the east uplink terminal to arm the central extraction lane.",
        type: "terminal",
        position: v3(14, 0.1, -11),
        holdDuration: 0.8,
        rotation: -Math.PI * 0.84,
      },
    ],
    holdZones: [],
    jumpPads: [
      { id: "uplink-pad-left", label: "Catwalk Pad", position: v3(-9, 0.1, 7), radius: 1.5, impulse: v3(6.5, 8, -5) },
      { id: "uplink-pad-right", label: "Catwalk Pad", position: v3(9, 0.1, -7), radius: 1.5, impulse: v3(-6.5, 8, 5) },
    ],
    weaponPickups: [
      {
        id: "uplink-helix",
        weaponId: "helix-burst-rifle",
        label: "Helix Burst Rifle",
        detail: "Hold the catwalk with a precise 3-round burst.",
        position: v3(0, 2.9, 0),
      },
      {
        id: "uplink-rail",
        weaponId: "rail-lance",
        label: "Rail Lance",
        detail: "Piercing charge rifle on the far east flank.",
        position: v3(15, 0.1, -10),
      },
      {
        id: "uplink-arc-refill",
        weaponId: "arc-smg",
        label: "Arc SMG Refill",
        detail: "Duplicate pickup converts into SMG reserve ammo.",
        position: v3(-14, 0.1, 11),
      },
    ],
    extractionZone: {
      label: "Central Extract",
      hint: "Collapse back to mid and hold for pickup.",
      position: v3(0, 0.1, 0),
      radius: 2,
      holdDuration: 1.2,
    },
    objectiveDefensePoints: [v3(-10, 0.1, 8), v3(10, 0.1, -8), v3(0, 2.9, 0)],
    optionalObjectives: [
      {
        id: "uplink-overcharge-a",
        kind: "bonus-ring",
        label: "Overcharge A",
        hint: "Hold the west uplink past safe output for bonus score.",
        position: v3(-14, 0.1, 11),
        radius: 3.8,
        scoreValue: 260,
        holdDuration: 2.4,
        unlockObjectiveIndex: 0,
      },
      {
        id: "uplink-overcharge-b",
        kind: "bonus-ring",
        label: "Overcharge B",
        hint: "Stay in the east ring for the greed payout and hunter spawn.",
        position: v3(14, 0.1, -11),
        radius: 3.8,
        scoreValue: 320,
        holdDuration: 2.8,
        unlockObjectiveIndex: 1,
        linkedSpawnIds: ["uplink-hunter-left", "uplink-hunter-right"],
      },
      {
        id: "uplink-catwalk-cache",
        kind: "bonus-cache",
        label: "Precision Cache",
        hint: "Cross the catwalk and cash the precision route with Helix or Rail.",
        position: v3(0, 2.9, 0),
        radius: 2.2,
        scoreValue: 240,
        requiresWeaponIds: ["helix-burst-rifle", "rail-lance"],
      },
    ],
    medalThresholds: {
      bronze: 2200,
      silver: 2700,
      gold: 3300,
      s: 3950,
      targetTime: 74,
    },
    checkpoints: [
      {
        id: "uplink-start",
        label: "Network Entry",
        objectiveIndex: 0,
        spawn: { position: v3(0, 0.1, 14), rotation: 0 },
      },
      {
        id: "uplink-mid",
        label: "Catwalk Split",
        objectiveIndex: 1,
        spawn: { position: v3(0, 0.1, 4), rotation: 0 },
      },
    ],
    bossEncounter: {
      bossId: "uplink-overseer",
      displayName: "Uplink Overseer",
      weaponType: "siege-mortar",
      spawn: { position: v3(0, 2.9, 0), rotation: Math.PI },
      checkpoint: { position: v3(0, 0.1, 4), rotation: Math.PI },
      lockdownSegments: [
        { id: "uplink-lock-west", position: v3(-17.2, 1.3, 0), size: v3(0.6, 2.6, 12), color: 0x8ce5ff },
        { id: "uplink-lock-east", position: v3(17.2, 1.3, 0), size: v3(0.6, 2.6, 12), color: 0x8ce5ff },
        { id: "uplink-lock-north", position: v3(0, 1.3, -13.8), size: v3(11, 2.6, 0.6), color: 0x8ce5ff },
        { id: "uplink-lock-south", position: v3(0, 1.3, 13.8), size: v3(11, 2.6, 0.6), color: 0x8ce5ff },
      ],
      health: 660,
      scoreValue: 1100,
      xpValue: 140,
      introText: "Uplink Overseer deployed. Siege battery live.",
    },
  },
  "blackout-run": {
    id: "blackout-run",
    name: "Blackout Run",
    subtitle: "Trigger the reactor. Escape the collapse.",
    objectiveKind: "switch-escape",
    floorSize: new THREE.Vector2(24, 62),
    floorColor: 0x23262e,
    backgroundColor: 0x0d1626,
    fogFar: 70,
    spawnPoints: [
      { position: v3(0, 0.1, 24), rotation: 0 },
      { position: v3(0, 0.1, 24), rotation: 0 },
    ],
    structures: [
      { id: "blackout-pocket-a-left", size: v3(4, 2.2, 6), position: v3(-6.5, 0, 15), color: 0x69401b, role: "cover" },
      { id: "blackout-pocket-a-right", size: v3(4, 2.2, 6), position: v3(6.5, 0, 9), color: 0x69401b, role: "cover" },
      { id: "blackout-pocket-b-left", size: v3(4, 2.4, 7), position: v3(-6.5, 0, -2), color: 0x535d70, role: "cover" },
      { id: "blackout-pocket-b-right", size: v3(4, 2.4, 7), position: v3(6.5, 0, -10), color: 0x535d70, role: "cover" },
      { id: "blackout-reactor-wall", size: v3(14, 2.8, 2), position: v3(0, 0, -20), color: 0x55647d, role: "wall" },
      { id: "blackout-reactor-cover", size: v3(5, 1.4, 2), position: v3(0, 0, -12), color: 0x6a4c2f, role: "cover" },
      { id: "blackout-slide-1-top", size: v3(5.2, 0.85, 1.8), position: v3(0, 1.12, 6), color: 0x5a6680, role: "overhead" },
      { id: "blackout-slide-1-left", size: v3(1, 2.2, 2), position: v3(-3.1, 0, 6), color: 0x434c60, role: "wall" },
      { id: "blackout-slide-1-right", size: v3(1, 2.2, 2), position: v3(3.1, 0, 6), color: 0x434c60, role: "wall" },
      { id: "blackout-slide-2-top", size: v3(5.2, 0.85, 1.8), position: v3(0, 1.12, 18), color: 0x5a6680, role: "overhead" },
      { id: "blackout-slide-2-left", size: v3(1, 2.2, 2), position: v3(-3.1, 0, 18), color: 0x434c60, role: "wall" },
      { id: "blackout-slide-2-right", size: v3(1, 2.2, 2), position: v3(3.1, 0, 18), color: 0x434c60, role: "wall" },
    ],
    navWaypoints: [
      v3(0, 0.1, 23),
      v3(-10, 0.1, 16),
      v3(10, 0.1, 10),
      v3(-9, 0.1, -2),
      v3(9, 0.1, -8),
      v3(0, 0.1, -18),
    ],
    botSpawns: [
      {
        id: "blackout-bot-1",
        spawn: { position: v3(-8, 0.1, 14), rotation: Math.PI / 2 },
        archetype: "disruptor",
        patrolRoute: [v3(-8, 0.1, 14), v3(-10, 0.1, 4), v3(-8, 0.1, -4), v3(0, 0.1, -16)],
      },
      {
        id: "blackout-bot-2",
        spawn: { position: v3(8, 0.1, -6), rotation: -Math.PI / 2 },
        archetype: "anchor",
        patrolRoute: [v3(8, 0.1, -6), v3(8, 0.1, -14), v3(4, 0.1, -18), v3(-4, 0.1, -18)],
      },
    ],
    reinforcementSpawns: [
      {
        id: "blackout-bot-3",
        spawn: { position: v3(8, 0.1, 8), rotation: Math.PI },
        archetype: "rusher",
        patrolRoute: [v3(8, 0.1, 8), v3(2, 0.1, 14), v3(0, 0.1, 24), v3(-6, 0.1, 12)],
      },
      {
        id: "blackout-bot-4",
        spawn: { position: v3(-8, 0.1, 2), rotation: 0 },
        archetype: "disruptor",
        patrolRoute: [v3(-8, 0.1, 2), v3(-9, 0.1, 14), v3(-4, 0.1, 24), v3(3, 0.1, 16)],
      },
      {
        id: "blackout-bot-5",
        spawn: { position: v3(0, 0.1, 20), rotation: Math.PI },
        archetype: "rusher",
        elite: true,
        patrolRoute: [v3(0, 0.1, 20), v3(0, 0.1, 12), v3(0, 0.1, 4), v3(0, 0.1, -8)],
      },
    ],
    interactables: [
      {
        id: "reactor-switch",
        label: "Reactor Switch",
        hint: "Trip the reactor. The evac clock starts immediately.",
        type: "switch",
        position: v3(0, 0.1, -23),
        holdDuration: 0.8,
        rotation: 0,
      },
    ],
    holdZones: [],
    jumpPads: [
      { id: "blackout-pad-1", label: "Return Pad", position: v3(-9, 0.1, -12), radius: 1.5, impulse: v3(8.5, 7.6, 8.5) },
      { id: "blackout-pad-2", label: "Return Pad", position: v3(9, 0.1, 0), radius: 1.5, impulse: v3(-8.5, 7.6, 9) },
    ],
    weaponPickups: [
      {
        id: "blackout-plasma",
        weaponId: "plasma-lobber",
        label: "Plasma Lobber",
        detail: "Splash launcher parked beside reactor cover.",
        position: v3(0, 0.1, -12),
      },
      {
        id: "blackout-scatter-refill",
        weaponId: "scattershot",
        label: "Scattershot Refill",
        detail: "Duplicate pickup grants shells for the evac pocket.",
        position: v3(-9, 0.1, -12),
      },
      {
        id: "blackout-rail-refill",
        weaponId: "rail-lance",
        label: "Rail Lance Refill",
        detail: "Charge ammo reserve placed along the evac lane.",
        position: v3(0, 0.1, 20),
      },
    ],
    extractionZone: {
      label: "Evac",
      hint: "Sprint back to evac and hold before the collapse catches you.",
      position: v3(0, 0.1, 24),
      radius: 2.1,
      holdDuration: 1.2,
    },
    objectiveDefensePoints: [v3(0, 0.1, -18), v3(-6, 0.1, 10), v3(6, 0.1, 10)],
    escapeDuration: 35,
    optionalObjectives: [
      {
        id: "blackout-overload",
        kind: "overload-node",
        label: "Overload Node",
        hint: "Hit the overload switch after the reactor to amplify the final bank.",
        position: v3(8, 0.1, -4),
        radius: 1.8,
        scoreValue: 420,
        holdDuration: 0.75,
        onlyAfterInteractableId: "reactor-switch",
      },
      {
        id: "blackout-escape-cache",
        kind: "bonus-cache",
        label: "Collapse Cache",
        hint: "Grab the mid-lane score cache while the evac route is live.",
        position: v3(9, 0.1, 0),
        radius: 1.7,
        scoreValue: 240,
        onlyAfterExtractionUnlocked: true,
      },
      {
        id: "blackout-hot-evac",
        kind: "timed-extract",
        label: "Hot Evac",
        hint: "Finish the escape with combo intact before the target split expires.",
        position: v3(0, 0.1, 24),
        radius: 2.4,
        scoreValue: 360,
        onlyAfterExtractionUnlocked: true,
        timeLimit: 48,
      },
    ],
    medalThresholds: {
      bronze: 2550,
      silver: 3150,
      gold: 3850,
      s: 4550,
      targetTime: 50,
    },
    checkpoints: [
      {
        id: "blackout-start",
        label: "Collapse Entry",
        objectiveIndex: 0,
        spawn: { position: v3(0, 0.1, 24), rotation: 0 },
      },
      {
        id: "blackout-reactor",
        label: "Reactor Breach",
        objectiveIndex: 1,
        spawn: { position: v3(0, 0.1, -10), rotation: Math.PI },
      },
    ],
    bossEncounter: {
      bossId: "blackout-hunter",
      displayName: "Blackout Hunter",
      weaponType: "phase-rail",
      spawn: { position: v3(0, 0.1, -18), rotation: 0 },
      checkpoint: { position: v3(0, 0.1, -10), rotation: Math.PI },
      lockdownSegments: [
        { id: "blackout-lock-reactor", position: v3(0, 1.3, -24), size: v3(9, 2.6, 0.6), color: 0xa9d6ff },
        { id: "blackout-lock-mid-left", position: v3(-10.8, 1.3, -6), size: v3(0.6, 2.6, 10), color: 0xa9d6ff },
        { id: "blackout-lock-mid-right", position: v3(10.8, 1.3, -6), size: v3(0.6, 2.6, 10), color: 0xa9d6ff },
      ],
      health: 760,
      scoreValue: 1300,
      xpValue: 160,
      introText: "Blackout Hunter inbound. Rail line charging.",
      escapeDurationAfterKill: 28,
    },
  },
};

export function cloneLevelDefinition(level: LevelDefinition): LevelDefinition {
  return {
    ...level,
    floorSize: level.floorSize.clone(),
    spawnPoints: level.spawnPoints.map((entry) => ({
      ...entry,
      position: entry.position.clone(),
    })),
    structures: level.structures.map((entry) => ({
      ...entry,
      size: entry.size.clone(),
      position: entry.position.clone(),
    })),
    navWaypoints: level.navWaypoints.map((entry) => entry.clone()),
    botSpawns: level.botSpawns.map((entry) => ({
      ...entry,
      spawn: {
        ...entry.spawn,
        position: entry.spawn.position.clone(),
      },
      patrolRoute: entry.patrolRoute.map((point) => point.clone()),
    })),
    reinforcementSpawns: level.reinforcementSpawns?.map((entry) => ({
      ...entry,
      spawn: {
        ...entry.spawn,
        position: entry.spawn.position.clone(),
      },
      patrolRoute: entry.patrolRoute.map((point) => point.clone()),
    })),
    interactables: level.interactables.map((entry) => ({
      ...entry,
      position: entry.position.clone(),
    })),
    holdZones: level.holdZones.map((entry) => ({
      ...entry,
      position: entry.position.clone(),
    })),
    jumpPads: level.jumpPads.map((entry) => ({
      ...entry,
      position: entry.position.clone(),
      impulse: entry.impulse.clone(),
    })),
    weaponPickups: level.weaponPickups.map((entry) => ({
      ...entry,
      position: entry.position.clone(),
    })),
    extractionZone: {
      ...level.extractionZone,
      position: level.extractionZone.position.clone(),
    },
    objectiveDefensePoints: level.objectiveDefensePoints?.map((entry) => entry.clone()),
    optionalObjectives: level.optionalObjectives.map((entry) => ({
      ...entry,
      position: entry.position.clone(),
    })),
    checkpoints: level.checkpoints.map((entry) => ({
      ...entry,
      spawn: {
        ...entry.spawn,
        position: entry.spawn.position.clone(),
      },
    })),
    bossEncounter: {
      ...level.bossEncounter,
      spawn: {
        ...level.bossEncounter.spawn,
        position: level.bossEncounter.spawn.position.clone(),
      },
      checkpoint: {
        ...level.bossEncounter.checkpoint,
        position: level.bossEncounter.checkpoint.position.clone(),
      },
      lockdownSegments: level.bossEncounter.lockdownSegments.map((entry) => ({
        ...entry,
        position: entry.position.clone(),
        size: entry.size.clone(),
      })),
    },
  };
}
