import {
  WeaponDefinition,
  WeaponId,
  WeaponInstance,
} from "./types";

export const STARTER_WEAPON_ID: WeaponId = "vanguard-carbine";

export const WEAPON_DEFINITIONS: Record<WeaponId, WeaponDefinition> = {
  "vanguard-carbine": {
    id: "vanguard-carbine",
    name: "Vanguard Carbine",
    shortName: "Carbine",
    pickupLabel: "Vanguard Carbine",
    pickupDetail: "Balanced automatic rifle for mid-range lanes.",
    fireMode: "auto",
    damage: 22,
    fireRate: 0.11,
    range: 100,
    magazineSize: 28,
    maxReserveAmmo: 112,
    reloadTime: 1.45,
    color: 0x8cc9ff,
    emissive: 0x255d92,
    tracerColor: 0xffbf66,
    tracerWidth: 0.042,
    moveSpread: 0.008,
    recoil: 0.82,
    cameraRecoil: {
      pitchDeg: 0.35,
      yawDeg: 0.06,
      rollDeg: 0.12,
      backOffset: 0.012,
      dropOffset: 0.002,
      attack: 38,
      recover: 16,
      yawVariance: 0.25,
    },
    scoreRole: "balanced rifle",
    scoreHint: "Reliable mid-range damage with controllable climb.",
  },
  "arc-smg": {
    id: "arc-smg",
    name: "Arc SMG",
    shortName: "Arc SMG",
    pickupLabel: "Arc SMG",
    pickupDetail: "High-output flank weapon with aggressive bloom.",
    fireMode: "auto",
    damage: 11,
    fireRate: 0.055,
    range: 72,
    magazineSize: 36,
    maxReserveAmmo: 144,
    reloadTime: 1.25,
    color: 0x7ff7ff,
    emissive: 0x1f7d8a,
    tracerColor: 0x9df9ff,
    tracerWidth: 0.034,
    moveSpread: 0.018,
    recoil: 0.52,
    cameraRecoil: {
      pitchDeg: 0.22,
      yawDeg: 0.05,
      rollDeg: 0.09,
      backOffset: 0.009,
      dropOffset: 0.001,
      attack: 42,
      recover: 18,
      yawVariance: 0.3,
    },
    scoreRole: "entry fragger",
    scoreHint: "Fast spray for short flanks and cleanup.",
    spread: 0.018,
    adsSpeed: 14,
  },
  "scattershot": {
    id: "scattershot",
    name: "Scattershot",
    shortName: "Scatter",
    pickupLabel: "Scattershot",
    pickupDetail: "Seven-pellet room clearer for close pushes.",
    fireMode: "scatter",
    damage: 9,
    fireRate: 0.78,
    range: 34,
    magazineSize: 8,
    maxReserveAmmo: 32,
    reloadTime: 1.78,
    color: 0xffcb82,
    emissive: 0x8f5320,
    tracerColor: 0xffd9a6,
    tracerWidth: 0.03,
    moveSpread: 0.02,
    recoil: 1.18,
    cameraRecoil: {
      pitchDeg: 0.75,
      yawDeg: 0.09,
      rollDeg: 0.18,
      backOffset: 0.022,
      dropOffset: 0.004,
      attack: 28,
      recover: 12,
      yawVariance: 0.18,
    },
    scoreRole: "breach weapon",
    scoreHint: "Heavy close-range burst for room clears.",
    pellets: 7,
    spread: 0.1,
  },
  "helix-burst-rifle": {
    id: "helix-burst-rifle",
    name: "Helix Burst Rifle",
    shortName: "Helix",
    pickupLabel: "Helix Burst Rifle",
    pickupDetail: "Controlled 3-round burst rifle for long lanes.",
    fireMode: "burst",
    damage: 16,
    fireRate: 0.42,
    range: 110,
    magazineSize: 24,
    maxReserveAmmo: 96,
    reloadTime: 1.58,
    color: 0xb89dff,
    emissive: 0x52329c,
    tracerColor: 0xdfcbff,
    tracerWidth: 0.036,
    moveSpread: 0.006,
    recoil: 0.74,
    cameraRecoil: {
      pitchDeg: 0.32,
      yawDeg: 0.05,
      rollDeg: 0.1,
      backOffset: 0.011,
      dropOffset: 0.002,
      attack: 36,
      recover: 16,
      yawVariance: 0.2,
    },
    scoreRole: "precision burst rifle",
    scoreHint: "Controlled volleys for lane anchoring.",
    burstCount: 3,
    burstInterval: 0.05,
  },
  "rail-lance": {
    id: "rail-lance",
    name: "Rail Lance",
    shortName: "Rail",
    pickupLabel: "Rail Lance",
    pickupDetail: "Charge, pierce, and punish exposed lines.",
    fireMode: "charge",
    damage: 85,
    fireRate: 0.9,
    range: 120,
    magazineSize: 5,
    maxReserveAmmo: 20,
    reloadTime: 1.9,
    color: 0xff8fe7,
    emissive: 0x8d2e82,
    tracerColor: 0xffb6f2,
    tracerWidth: 0.06,
    moveSpread: 0,
    recoil: 1.05,
    cameraRecoil: {
      pitchDeg: 0.62,
      yawDeg: 0.04,
      rollDeg: 0.08,
      backOffset: 0.018,
      dropOffset: 0.003,
      attack: 24,
      recover: 10,
      yawVariance: 0.12,
    },
    scoreRole: "anti-line pick",
    scoreHint: "Charge shots reward clean sightlines.",
    chargeTime: 0.65,
    minChargeDamage: 35,
    maxChargeDamage: 85,
    maxPierce: 2,
    adsSpeed: 8,
  },
  "plasma-lobber": {
    id: "plasma-lobber",
    name: "Plasma Lobber",
    shortName: "Plasma",
    pickupLabel: "Plasma Lobber",
    pickupDetail: "Arcing payload launcher for splash pressure.",
    fireMode: "projectile",
    damage: 40,
    fireRate: 0.95,
    range: 60,
    magazineSize: 6,
    maxReserveAmmo: 18,
    reloadTime: 1.95,
    color: 0x88ffb6,
    emissive: 0x2c8b57,
    tracerColor: 0x88ffb6,
    tracerWidth: 0.055,
    moveSpread: 0.012,
    recoil: 0.96,
    cameraRecoil: {
      pitchDeg: 0.58,
      yawDeg: 0.07,
      rollDeg: 0.15,
      backOffset: 0.017,
      dropOffset: 0.003,
      attack: 24,
      recover: 11,
      yawVariance: 0.16,
    },
    scoreRole: "area denial launcher",
    scoreHint: "Arcing splash pressure around cover.",
    projectileSpeed: 24,
    projectileGravity: 13,
    projectileLifetime: 3.8,
    splashRadius: 2.6,
    splashDamage: 30,
  },
  "phantom-sniper": {
    id: "phantom-sniper",
    name: "Phantom Sniper",
    shortName: "Phantom",
    pickupLabel: "Phantom Sniper",
    pickupDetail: "Bolt-action precision rifle for long-range picks.",
    fireMode: "semi",
    damage: 110,
    fireRate: 1.3,
    range: 150,
    magazineSize: 5,
    maxReserveAmmo: 20,
    reloadTime: 2.8,
    color: 0x6b8ccc,
    emissive: 0x2a3d5c,
    tracerColor: 0xa8c4e6,
    tracerWidth: 0.055,
    moveSpread: 0.03,
    recoil: 1.4,
    cameraRecoil: {
      pitchDeg: 0.85,
      yawDeg: 0.03,
      rollDeg: 0.06,
      backOffset: 0.024,
      dropOffset: 0.005,
      attack: 22,
      recover: 9,
      yawVariance: 0.08,
    },
    scoreRole: "precision pick",
    scoreHint: "One-shot kills reward patience and positioning.",
    maxPierce: 1,
    adsZoomFactor: 0.35,
    adsSpeed: 7,
  },
};

export function getWeaponDefinition(weaponId: WeaponId): WeaponDefinition {
  return WEAPON_DEFINITIONS[weaponId];
}

export function createWeaponInstance(weaponId: WeaponId): WeaponInstance {
  const def = getWeaponDefinition(weaponId);
  return {
    id: weaponId,
    ammo: def.magazineSize,
    reserveAmmo: def.maxReserveAmmo,
  };
}
